### ISSUE TITLE
Race condition 

### ISSUE THREAD

**Issue by rakan-dev** [rasta-mouse/SharpC2#12]
Issue : Race Condition in Task Shell 

task sent and running result come and disappear 
i think drone sent this frames:
1- Task running with result 
2- Task completed with result 
3- Task running with result 

so there is no result in Client sometimes

image:
![race condition 2](https://user-images.githubusercontent.com/36914816/219678780-973e8455-cbe0-48fa-92a7-a9be1f2008c7.png)

**Comment by tbaker57** [comment]
I'm not sure about the 'shell' command, but I've experienced a similar issue (output completes with RUNNING status) with 'execute-assembly'. Very rarely the drone will send the complete output with TaskStatus=Running. Debugging ExecuteAssembly.cs it looks like the code below sometimes returns without sending a COMPLETE status because there is no more output:
 
        if (t.ThreadState is ThreadState.Stopped or ThreadState.Aborted)
        {
            if (output.Length > 0)
                await Drone.SendTaskOutput(new TaskOutput(task.Id, TaskStatus.COMPLETE, output));
            // XXX sometimes the thread finishes with output.Length==0
            return;
        }

I'm not quite sure why there is a check for output.Length >0 here but in my testing,  occasionally this code was reached with output.Length==0 and so the task was left in the RUNNING state. The output from the execution was definitely sent to the TeamServer in the do-while loop - it just doesn't get rendered in the client. due to the above issue.

cheers, Tim

**Comment by tbaker57** [comment]
By running Client, TeamServer and drone all on the same box I can reproduce the race condition in 'shell' fairly consistently. With some debug statements in TeamServer.Modules.TaskOutputModule you can see (as @rakan-dev  pointed out above) that sometimes the C2Frame with Task.Status=COMPLETE arrives _before_ the final few Task.Status=RUNNING frames and also the Task.Status=RUNNING frames (with 1 line of cmd.exe output per frame) arrive in random order, I'm guessing because of the asynchronous calls to Drone.SendTaskOutput as each line of cmd output is generated.

My (admittedly terrible) workaround for this is to buffer all the cmd output in the drone in a StringBuilder and then send all the output on the final call to Drone.SendTaskOutput. In Shell.cs:

<pre>
+         StringBuilder sb = new StringBuilder();
30c31
-         async void OnDataReceived(object sender, DataReceivedEventArgs e)
+         void OnDataReceived(object sender, DataReceivedEventArgs e)
32c33
-        await Drone.SendTaskOutput(new TaskOutput(task.Id, TaskStatus.RUNNING, e.Data + Environment.NewLine));
+        sb.Append(e.Data + Environment.NewLine);
61c63
-         await Drone.SendTaskComplete(task.Id);
+         await Drone.SendTaskOutput(new TaskOutput(task.Id, TaskStatus.COMPLETE, sb.ToString())); ;
</pre>

The downside of course is that you won't get any partial output for long-running commands, but for commands of short duration it seems to work.

**Comment by rasta-mouse** [comment]
@rakan-dev @tbaker57 this should be improved in the latest release.

**Comment by tbaker57** [comment]
Fixes it for me - thanks @rasta-mouse  ! :+1:
